services:
  - type: web
    name: kitchen-render-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: REPLICATE_API_TOKEN
        value: r8_0RoLEtZ6Xd5LsPYIP5m9uHPwsCt14Pm2hsj7Q
